version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "cur-app"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-ifrg8xymeizi"
s3_prefix = "cur-app"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = ["HelloWorldFunction=280444861259.dkr.ecr.us-east-1.amazonaws.com/curappacdddc19/helloworldfunction19d43fc4repo"]
